language: objective-c
xcode_sdk: iphonesimulator8.1
xcode_scheme: SRHackWeek-Travis
xcode_workspace: SRHackWeek.xcworkspace
before_install:
  - brew update
  - brew reinstall xctool
  - gem update cocoapods
  - gem install slather
after_success:
  - slather
