//
// SRSplashScreenAnimationView.h
// Generated by Core Animator version 1.0 on 3/17/15.
//
// DO NOT MODIFY THIS FILE. IT IS AUTO-GENERATED AND WILL BE OVERWRITTEN
//

#import <UIKit/UIKit.h>

IB_DESIGNABLE
@interface SRSplashScreenAnimationView : UIView

@property (strong, nonatomic) NSDictionary *viewsByName;

@property (weak, nonatomic) UIView * topButton;
@property (weak, nonatomic) UIImageView * bottomButton;
@property (weak, nonatomic) UIImageView * menuBackground;
@property (weak, nonatomic) UIImageView * logoView;

// showSplashMenu
- (void)addShowSplashMenuAnimation;
- (void)addShowSplashMenuAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addShowSplashMenuAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addShowSplashMenuAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addShowSplashMenuAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)removeShowSplashMenuAnimation;

// dismissSplashMenu
- (void)addDismissSplashMenuAnimation;
- (void)addDismissSplashMenuAnimationWithCompletion:(void (^)(BOOL finished))completionBlock;
- (void)addDismissSplashMenuAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion;
- (void)addDismissSplashMenuAnimationAndRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)addDismissSplashMenuAnimationWithBeginTime:(CFTimeInterval)beginTime andFillMode:(NSString *)fillMode andRemoveOnCompletion:(BOOL)removedOnCompletion completion:(void (^)(BOOL finished))completionBlock;
- (void)removeDismissSplashMenuAnimation;

- (void)removeAllAnimations;

@end